name: E2E
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS version 14
        uses: actions/setup-node@v1
        with:
          node-version: "14.16.0"

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
        build: yarn install
        start: yarn go
        wait-on-timeout: 300
        config-file: cypress.json
        wait-on: "http://localhost:3000"
        headless: true

      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
